### ISSUE TITLE
Missing file for pretrained model

### ISSUE THREAD

**Issue by chitianqilin** [youngwoo-yoon/Co-Speech_Gesture_Generation#11]
args.train_data_path[0] saved by the checkpoint_and_model indicates a missing file vocab_cache.pkl.

```Traceback (most recent call last):

  File "/snap/pycharm-community/281/plugins/python-ce/helpers/pydev/pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script

  File "/snap/pycharm-community/281/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)

  File "/.../Co-Speech_Gesture_Generation/scripts/inference.py", line 174, in <module>
    main(args.ckpt_path, args.transcript_path)

  File "/.../Co-Speech_Gesture_Generation/scripts/inference.py", line 106, in main
    with open(vocab_cache_path, 'rb') as f:

FileNotFoundError: [Errno 2] No such file or directory: `'/mnt/work3/GENEA22_dataset/v1/trn/lmdb/vocab_cache.pkl'```

**Comment by youngwoo-yoon** [comment]
Hello,
If you ran train.py, you should get vocab_cache.pkl. Please see this part https://github.com/youngwoo-yoon/Co-Speech_Gesture_Generation/blob/master/scripts/train.py#L178

**Comment by youngwoo-yoon** [comment]
Hello,
I just uploaded vocab_cahe file for the pretrained model. Please see the updated readme.
